import AppKit
import LNInterpolationFramework

let fromColor = #colorLiteral(red: 1, green: 1, blue: 0, alpha: 1)
let toColor = #colorLiteral(red: 0, green: 0, blue: 1, alpha: 1)

fromColor.interpolate(to: toColor, progress: 0.05)
fromColor.interpolate(to: toColor, progress: 0.1)
fromColor.interpolate(to: toColor, progress: 0.15)
fromColor.interpolate(to: toColor, progress: 0.2)
fromColor.interpolate(to: toColor, progress: 0.25)
fromColor.interpolate(to: toColor, progress: 0.3)
fromColor.interpolate(to: toColor, progress: 0.35)
fromColor.interpolate(to: toColor, progress: 0.4)
fromColor.interpolate(to: toColor, progress: 0.45)
fromColor.interpolate(to: toColor, progress: 0.5)
fromColor.interpolate(to: toColor, progress: 0.55)
fromColor.interpolate(to: toColor, progress: 0.6)
fromColor.interpolate(to: toColor, progress: 0.65)
fromColor.interpolate(to: toColor, progress: 0.7)
fromColor.interpolate(to: toColor, progress: 0.75)
fromColor.interpolate(to: toColor, progress: 0.8)
fromColor.interpolate(to: toColor, progress: 0.85)
fromColor.interpolate(to: toColor, progress: 0.9)
fromColor.interpolate(to: toColor, progress: 0.95)
fromColor.interpolate(to: toColor, progress: 1.0)

fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.05)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.1)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.15)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.2)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.25)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.3)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.35)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.4)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.45)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.5)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.55)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.6)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.65)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.7)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.75)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.8)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.85)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.9)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 0.95)
fromColor.interpolate(to: toColor, behavior:.useRGBColorSpace, progress: 1.0)
